### ISSUE TITLE
failed to find error in android studio

### ISSUE THREAD

**Issue by ThathaPavanNagaraju** [scottyab/AESCrypt-Android#10]
Error:Failed to find: com.scottyab:aescrypt:0.0.1
Open File "open.dependency.in.project.structure" Open in Project Structure

**Comment by scottyab** [comment]
There seem to be some maven central server issues at the moment, this could be related?

**Comment by scottyab** [comment]
Maven central seems to be responding again. Ensure you have `compile 'com.scottyab:aescrypt:0.0.1'`in your build.gradle file. If the problem continues, please reopen.

**Comment by ThathaPavanNagaraju** [comment]
its is still comming :/

**Comment by ThathaPavanNagaraju** [comment]
I solved it my gradle is offline
