### ISSUE TITLE
Use less Library Delete this Shit

### ISSUE THREAD

**Issue by Naguchennai** [scottyab/AESCrypt-Android#23]
After apk decompiler it clearly show all my string (jsoneditoronline.org)
 ex: this.encryptedMsg = AESCrypt.encrypt("url", "myurl");

Then why this useless library.. don't wast developer time .. just delete thus shit library

dont call this shit  encrypt and decrypt

**Comment by scottyab** [comment]
Some people just wanna troll. :(
