### ISSUE TITLE
please make the Library downloadable as jar !!!

### ISSUE THREAD

**Issue by mustii82** [scottyab/AESCrypt-Android#3]
not everybody use maven or gradle so please let other people download the library jar file.

**Comment by mustii82** [comment]
for everybody you can use the class in the source file its one simple class so the need of an external library isn't needed in my opinion

**Comment by scottyab** [comment]
You can download the aar from [maven central](https://search.maven.org/remotecontent?filepath=com/scottyab/aescrypt/0.0.1/aescrypt-0.0.1.aar) or you know compile it yourself ;)

**Comment by mustii82** [comment]
its easier to import the class of the source code and call it from the imported class or export the source code as a jar file and import it as library.
