### ISSUE TITLE
How to use aes256 mode?

### ISSUE THREAD

**Issue by Ghostish** [scottyab/AESCrypt-Android#4]
I use  AESCrypt.encrypt("123456","123456") and I got "LK09ZUQfjEWnBhyah8VNXg=="
but the result should be "U2FsdGVkX1/bIqQCoW3eTfBoynP0mswP1PE6HM97jTk=" .
What's the problem?

**Comment by ninjatrench** [comment]
Can you elaborate more ? @Ghostish

**Comment by scottyab** [comment]
Awaiting more info
