### ISSUE TITLE
Plain Text Error

### ISSUE THREAD

**Issue by pixelbendr** [scottyab/AESCrypt-Android#5]
Hello, Am using the library for a messaging app am working on. Before using the library messages are sent in plain text so after adding the library the decrypt message crashes the app for those old messages. Since the wrapped in the try catch block was expecting to catch the error for plain text. 
Need help please. :(

stack trace below

 Fatal Exception: java.lang.IllegalArgumentException 
Fatal Exception: java.lang.IllegalArgumentException: bad base-64
       at android.util.Base64.decode(Base64.java:161)
       at android.util.Base64.decode(Base64.java:136)
       at android.util.Base64.decode(Base64.java:118)
       at com.scottyab.aescrypt.AESCrypt.decrypt(AESCrypt.java:124)

**Comment by scottyab** [comment]
Hi, thanks for reporting this, i cannot help without examples of the input data and key you are using. Closing until more data providered
