### ISSUE TITLE
Is there any way to use it in Java Platform such as Windows?

### ISSUE THREAD

**Issue by gordonpro** [scottyab/AESCrypt-Android#6]
The Cipher "AES/CBC/PKCS7Padding" not support.

Only "AES/CBC/PKCS5Padding" is available

**Comment by scottyab** [comment]
Yeah, it's a single class library so just replacing `import android.util.Base64;` and `import android.util.Log;` are the only Android things and those can be found in java.  If you'd like to send a PR to make Java compatible I would be happy to accept. 

`AES/CBC/PKCS7Padding` is used for compatibility with AESCrypt. So if you need compatibility you'll need a security provider that supports it.
