### ISSUE TITLE
key derivation: use PBKDF2, not SHA-256

### ISSUE THREAD

**Issue by japdlsd** [scottyab/AESCrypt-Android#9]
the long explanation is here: [link to StackExchange](http://security.stackexchange.com/questions/16354/whats-the-advantage-of-using-pbkdf2-vs-sha256-to-generate-an-aes-encryption-key)

TL;DR SHA-256 was not meant as key derivation function and has some bad properties (e.g. it is too fast).

**Comment by scottyab** [comment]
Thanks for your comment, I agree, however the point of this library was Android version of https://github.com/Gurpartap/aescrypt 

I'll update the readme within something like... For better and just as simple API check out [java-aes-crypto(https://github.com/tozny/java-aes-crypto)
